name: End-to-end tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run E2E tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start:ci
          wait-on: "http://localhost:1234"